const express = require("express");
const app = express();
const cors = require("cors");
require("dotenv").config();
const sequelize = require("./util/database");
const User = require("./models/User");
const Expense = require("./models/Expense");
const Order = require("./models/Order");
const expenseRoutes = require("./routes/expense");
const authorisationRoutes = require("./routes/authorisation");
const purchaseRoutes = require("./routes/purchase");
const premiumRoutes = require("./routes/premiumfeatures");
const passwordRoutes = require("./routes/password");
User.hasMany(Expense);
Expense.belongsTo(User);
User.hasMany(Order);
Order.belongsTo(User);
app.use(cors());
app.use(express.json());
app.use(express.urlencoded({ extended: false }));
app.use(authorisationRoutes);
app.use(expenseRoutes);
app.use(purchaseRoutes);
app.use("/password", passwordRoutes);
app.use("/premium", premiumRoutes);
sequelize.sync().then((_) => {
  app.listen(3000);
});
